
export const items = [
  {
    itemId: 1,
    itemName: "Mens 500 underwear",
    category: "Underwear",
    brand: "Renoma",
    imgFront:
      "https://innerstatement.com.sg/cdn/shop/products/JMB157744AS1OPENAQ.jpg?v=1642040274&width=600",
    imgBack: [
      "https://m.media-amazon.com/images/I/51dBhAF9R9S._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/51dBhAF9R9S._AC_SX522_.jpg",
    ],
    itemSalestate: "light-orange;Hot",
    itemRating: 3,
    itemDesc: "Best fit underwear for men, cooling material and comfy style",
    itemSize: "S;M;L;XL;XXL",
    itemPricenew: "$10.50",
    itemPriceOld: "$15.80",
    itemWarranty: "2 years",
    itemPolicy: "-",
    itemDelivery: "Quick 1 week delivery",
    itemColor: [
      `rgb(${255}, ${255}, ${255})`,
      `rgb(${0}, ${0}, ${0})`,
      `rgb(${255}, ${165}, ${255})`,
    ],
    itemSKU: 908098908,
    itemAvailability: 340,
  },
  // Additional items
  {
    itemId: 2,
    itemName: "Women's Yoga Pants",
    category: "Activewear",
    brand: "FitFusion",
    imgFront: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/521771/01/fnd/SEA/fmt/png/Performance-Women's-Yoga-Training-Pants",
    imgBack: ["https://d1nymbkeomeoqg.cloudfront.net/photos/27/57/397200_16656_XXL.jpg","https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Yoda_Attack_of_the_Clones.png/255px-Yoda_Attack_of_the_Clones.png"],
    itemSalestate: "light-pink;New Collection",
    itemRating: 4,
    itemDesc: "Flexible and breathable yoga pants for active women",
    itemSize: "XS;S;M;L;XL",
    itemPricenew: "$29.99",
    itemPriceOld: "$39.99",
    itemWarranty: "1 year",
    itemPolicy: "Free returns within 30 days",
    itemDelivery: "Standard shipping in 3-5 business days",
    itemColor: [`rgb(${200}, ${100}, ${150})`, `rgb(${50}, ${50}, ${50})`],
    itemSKU: 87654321,
    itemAvailability: 150,
  },
  {
    itemId: 3,
    itemName: "Men's Casual T-Shirt",
    category: "Clothing",
    brand: "UrbanStyle",
    imgFront: "https://img.ws.mms.shopee.sg/aff15c8f621493059f9adec81b9d142d",
    imgBack: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbyAoeKXC7cHEC3tJtGTdZf_F8ujPyfXK1WQ&usqp=CAU","https://www.suss.edu.sg/images/default-source/content/ar/e-shop/sussold_thumbnail-(squared).png?sfvrsn=41109df0_2"],
    itemSalestate: "light-blue;Summer Collection",
    itemRating: 4,
    itemDesc: "Comfortable and trendy casual t-shirt for men",
    itemSize: "S;M;L;XL",
    itemPricenew: "$19.99",
    itemPriceOld: "$24.99",
    itemWarranty: "-",
    itemPolicy: "No returns on clearance items",
    itemDelivery: "Express shipping available",
    itemColor: [`rgb(${100}, ${200}, ${50})`, `rgb(${255}, ${200}, ${0})`],
    itemSKU: 76543210,
    itemAvailability: 80,
  },
  {
    itemId: 4,
    itemName: "Wireless Bluetooth Earbuds",
    category: "Electronics",
    brand: "SoundSync",
    imgFront: "https://www.sony.com.sg/image/6ff70f66ce935f02861635b3e936a70c?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF",
    imgBack: ["https://images.philips.com/is/image/PhilipsConsumer/SHB1700_97-IMS-en_SG?$jpglarge$&wid=1250","https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Yoda_Attack_of_the_Clones.png/255px-Yoda_Attack_of_the_Clones.png"],
    itemSalestate: "light-green;Limited Offer",
    itemRating: 5,
    itemDesc: "High-quality wireless earbuds with noise cancellation",
    itemSize: "-",
    itemPricenew: "$79.99",
    itemPriceOld: "$99.99",
    itemWarranty: "2 years",
    itemPolicy: "Free returns within 60 days",
    itemDelivery: "Free shipping worldwide",
    itemColor: [`rgb(${50}, ${50}, ${100})`, `rgb(${200}, ${100}, ${50})`],
    itemSKU: 12345678,
    itemAvailability: 200,
  },
  {
    itemId: 5,
    itemName: "Portable Power Bank",
    category: "Accessories",
    brand: "PowerUp",
    imgFront: "https://images.philips.com/is/image/PhilipsConsumer/DLP9516CB_69-IMS-en_SG?wid=420&hei=360&$jpglarge$",
    imgBack: ["https://www.funky.sg/cdn/shop/products/0_tbnail-no-logoII_700x700.jpg?v=1662435209","https://hips.hearstapps.com/hmg-prod/images/ghi-laptoppowerbanks-6453cd3d6ffbd.png?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*"],
    itemSalestate: "light-orange;Travel Essential",
    itemRating: 4,
    itemDesc: "Slim and powerful portable charger for on-the-go use",
    itemSize: "-",
    itemPricenew: "$34.50",
    itemPriceOld: "$49.99",
    itemWarranty: "1 year",
    itemPolicy: "Free returns within 30 days",
    itemDelivery: "Standard shipping in 3-5 business days",
    itemColor: [`rgb(${150}, ${150}, ${150})`, `rgb(${0}, ${0}, ${255})`],
    itemSKU: 98765432,
    itemAvailability: 120,
  },
  {
    itemId: 6,
    itemName: "Smart Watch",
    category: "Wearable Tech",
    brand: "TechGear",
    imgFront: "https://imilab.com.sg/wp-content/uploads/2022/07/IMG_7175.jpg",
    imgBack: ["https://m.media-amazon.com/images/I/61matl9KPFL.jpg", "https://hammeronline.in/cdn/shop/files/Hammerglidebluetoothcallingsmartwatch_1.webp?v=1694851875"],
    itemSalestate: "light-blue;New Arrival",
    itemRating: 4,
    itemDesc: "Advanced smartwatch with fitness tracking and app integration",
    itemSize: "-",
    itemPricenew: "$129.99",
    itemPriceOld: "$149.99",
    itemWarranty: "2 years",
    itemPolicy: "Free returns within 45 days",
    itemDelivery: "Fast shipping worldwide",
    itemColor: [`rgb(${100}, ${200}, ${50})`, `rgb(${255}, ${0}, ${0})`],
    itemSKU: 23456789,
    itemAvailability: 90,
  },
  {
    itemId: 7,
    itemName: "Digital Camera",
    category: "Electronics",
    brand: "PhotoPro",
    imgFront: "https://www.mscolor.com.sg/wp-content/uploads/2022/08/1624972877_1649280.jpg",
    imgBack: ["https://photographylife.com/wp-content/uploads/2018/07/Back-Button-Focusing.jpg","https://fujifilm-x.com/wp-content/uploads/2021/01/gfx100s_thum_egsv.jpg"],
    itemSalestate: "light-green;Professional Grade",
    itemRating: 5,
    itemDesc: "High-resolution digital camera for stunning photography",
    itemSize: "-",
    itemPricenew: "$699.99",
    itemPriceOld: "$799.99",
    itemWarranty: "3 years",
    itemPolicy: "No returns on clearance items",
    itemDelivery: "Express shipping available",
    itemColor: [`rgb(${0}, ${100}, ${200})`, `rgb(${255}, ${150}, ${0})`],
    itemSKU: 34567890,
    itemAvailability: 30,
  },
  {
    itemId: 8,
    itemName: "Gaming Console",
    category: "Gaming",
    brand: "GameMaster",
    imgFront: "https://m.media-amazon.com/images/I/51BIdV4YzNL.jpg",
    imgBack: ["https://media.gamestop.com/i/gamestop/20006341/Microsoft-Xbox-Series-S-Digital-Console-1TB---Black"],
    itemSalestate: "light-orange;Limited Edition",
    itemRating: 4,
    itemDesc: "Powerful gaming console for immersive gameplay",
    itemSize: "-",
    itemPricenew: "$449.99",
    itemPriceOld: "$499.99",
    itemWarranty: "2 years",
    itemPolicy: "Free returns within 60 days",
    itemDelivery: "Free shipping worldwide",
    itemColor: [`rgb(${0}, ${0}, ${0})`, `rgb(${150}, ${50}, ${200})`],
    itemSKU: 45678901,
    itemAvailability: 50,
  },
  {
    itemId: 9,
    itemName: "Running Shoes",
    category: "Shoes",
    brand: "RunElite",
    imgFront: "https://underarmour.scene7.com/is/image/Underarmour/3025425-001_DETAIL5?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
    imgBack: ["https://underarmour.scene7.com/is/image/Underarmour/3025581-001_DETAIL5?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688"],
    itemSalestate: "light-pink;Running Collection",
    itemRating: 4,
    itemDesc: "High-performance running shoes for athletes",
    itemSize: "US 5;US 6;US 7;US 8;US 9",
    itemPricenew: "$89.99",
    itemPriceOld: "$109.99",
    itemWarranty: "1 year",
    itemPolicy: "Free returns within 30 days",
    itemDelivery: "Standard shipping in 3-5 business days",
    itemColor: [`rgb(${50}, ${150}, ${200})`, `rgb(${255}, ${0}, ${150})`],
    itemSKU: 56789012,
    itemAvailability: 70,
  },
  {
    itemId: 10,
    itemName: "Wireless Keyboard",
    category: "Computer Accessories",
    brand: "TechEase",
    imgFront: "https://i5.walmartimages.com/seo/Gaming-Keyboard-Mouse-104-Keys-Rainbow-LED-RGB-Backlit-Quiet-Computer-Keyboard-Multimedia-Keys-26-Anti-ghosting-Waterproof-Light-Up-USB-Wired-PC-Game_329edf0a-57ab-4fb8-8a65-5f23dba97fc3.e87d65062baeebc7e8989760a1d8f49a.jpeg",
    imgBack: ["https://m.media-amazon.com/images/I/71d7UKkg6xL._AC_SL1500_.jpg"],
    itemSalestate: "light-blue;Office Essential",
    itemRating: 4,
    itemDesc: "Sleek and efficient wireless keyboard-mouse combo",
    itemSize: "-",
    itemPricenew: "$49.99",
    itemPriceOld: "$59.99",
    itemWarranty: "2 years",
    itemPolicy: "Free returns within 45 days",
    itemDelivery: "Fast shipping worldwide",
    itemColor: [`rgb(${0}, ${0}, ${0})`, `rgb(${100}, ${200}, ${50})`],
    itemSKU: 67890123,
    itemAvailability: 100,
  },
];
  
